from __future__ import annotations

import argparse
import asyncio
import json
import subprocess
import tempfile
import wave
from pathlib import Path
from typing import Any

from baby_care_api.services.audio_decoder import (
    MAX_DECODED_BYTES,
    MAX_INPUT_BYTES,
    AudioDecodeError,
    FfmpegAudioDecoder,
)

FFMPEG = Path("/usr/local/bin/ffmpeg")
FFPROBE = Path("/usr/local/bin/ffprobe")


def _run(*arguments: str, timeout: float = 30) -> None:
    completed = subprocess.run(
        [str(FFMPEG), "-nostdin", "-hide_banner", "-loglevel", "error", *arguments],
        check=False,
        stdin=subprocess.DEVNULL,
        capture_output=True,
        timeout=timeout,
        shell=False,
    )
    if completed.returncode != 0:
        raise RuntimeError("Synthetic audio fixture generation failed")


def _tone_input(*, duration: float = 1.25, rate: int = 16_000) -> list[str]:
    return [
        "-f",
        "lavfi",
        "-i",
        f"sine=frequency=440:sample_rate={rate}:duration={duration}",
    ]


def _generate_inputs(directory: Path) -> dict[str, tuple[Path, str, str]]:
    fixtures = {
        "wav": (directory / "tone-wav", "audio/wav", "pcm_s16le"),
        "webm_opus": (directory / "tone-webm", "audio/webm", "opus"),
        "mp4_aac": (directory / "tone-mp4", "audio/mp4", "aac"),
        "raw_aac": (directory / "tone-aac", "audio/aac", "aac"),
    }
    _run(
        *_tone_input(), "-ac", "1", "-c:a", "pcm_s16le", "-f", "wav", "-y", str(fixtures["wav"][0])
    )
    _run(
        *_tone_input(),
        "-ac",
        "1",
        "-c:a",
        "libopus",
        "-f",
        "webm",
        "-y",
        str(fixtures["webm_opus"][0]),
    )
    _run(*_tone_input(), "-ac", "1", "-c:a", "aac", "-f", "mp4", "-y", str(fixtures["mp4_aac"][0]))
    _run(*_tone_input(), "-ac", "1", "-c:a", "aac", "-f", "adts", "-y", str(fixtures["raw_aac"][0]))
    return fixtures


async def _expect_error(
    decoder: FfmpegAudioDecoder,
    source: Path,
    destination: Path,
    *,
    mime_type: str,
    expected: str,
    max_seconds: int = 5,
) -> None:
    try:
        await decoder.decode(
            source,
            destination,
            declared_mime_type=mime_type,
            max_seconds=max_seconds,
        )
    except AudioDecodeError as exc:
        if exc.code != expected:
            raise AssertionError(f"Expected {expected}, received {exc.code}") from exc
    else:
        raise AssertionError(f"Expected {expected}")


async def _verify() -> dict[str, Any]:
    decoder = FfmpegAudioDecoder(ffmpeg_path=FFMPEG, ffprobe_path=FFPROBE)
    if not decoder.configured:
        raise RuntimeError("Pinned FFmpeg binaries are unavailable")

    with tempfile.TemporaryDirectory(prefix="baby-care-decoder-smoke-") as temporary:
        directory = Path(temporary)
        fixtures = _generate_inputs(directory)
        accepted: dict[str, dict[str, Any]] = {}
        for name, (source, mime_type, expected_codec) in fixtures.items():
            destination = directory / f"{name}-decoded"
            decoded = await decoder.decode(
                source,
                destination,
                declared_mime_type=mime_type,
                max_seconds=5,
            )
            if decoded.codec != expected_codec or decoded.source_mime_type != mime_type:
                raise AssertionError("Decoded identity did not match the generated bytes")
            expected_rate = 48_000 if name == "webm_opus" else 16_000
            if decoded.sample_rate_hz != expected_rate or decoded.channels != 1:
                raise AssertionError("B-05 unexpectedly resampled or downmixed the input")
            if decoded.rejection_code is not None or decoded.quality_reasons:
                raise AssertionError("Usable synthetic tone was rejected")
            with wave.open(str(destination), "rb") as pcm:
                if pcm.getsampwidth() != 2:
                    raise AssertionError("PCM derivative was not signed 16-bit WAV")
            accepted[name] = {
                "container": decoded.container,
                "codec": decoded.codec,
                "sample_rate_hz": decoded.sample_rate_hz,
                "channels": decoded.channels,
            }

        await _expect_error(
            decoder,
            fixtures["webm_opus"][0],
            directory / "spoofed-pcm",
            mime_type="audio/wav",
            expected="UNSUPPORTED_CODEC",
        )

        video = directory / "video-mp4"
        _run(
            "-f",
            "lavfi",
            "-i",
            "color=size=16x16:rate=1:duration=2",
            *_tone_input(duration=2),
            "-map",
            "0:v:0",
            "-map",
            "1:a:0",
            "-c:v",
            "mpeg4",
            "-c:a",
            "aac",
            "-f",
            "mp4",
            "-y",
            str(video),
        )
        await _expect_error(
            decoder,
            video,
            directory / "video-pcm",
            mime_type="audio/mp4",
            expected="UNSUPPORTED_CODEC",
        )

        multitrack = directory / "multitrack-webm"
        _run(
            *_tone_input(),
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=660:sample_rate=16000:duration=1.25",
            "-map",
            "0:a:0",
            "-map",
            "1:a:0",
            "-c:a",
            "libopus",
            "-f",
            "webm",
            "-y",
            str(multitrack),
        )
        await _expect_error(
            decoder,
            multitrack,
            directory / "multitrack-pcm",
            mime_type="audio/webm",
            expected="UNSUPPORTED_CODEC",
        )

        flac = directory / "unsupported-flac"
        _run(*_tone_input(), "-c:a", "flac", "-f", "flac", "-y", str(flac))
        await _expect_error(
            decoder,
            flac,
            directory / "unsupported-pcm",
            mime_type="audio/wav",
            expected="UNSUPPORTED_CODEC",
        )

        malformed = directory / "malformed"
        malformed.write_bytes(b"not-an-audio-container")
        await _expect_error(
            decoder,
            malformed,
            directory / "malformed-pcm",
            mime_type="audio/wav",
            expected="DECODE_ERROR",
        )

        too_large = directory / "too-large"
        with too_large.open("wb") as output:
            output.truncate(MAX_INPUT_BYTES + 1)
        await _expect_error(
            decoder,
            too_large,
            directory / "too-large-pcm",
            mime_type="audio/wav",
            expected="TOO_LARGE",
        )

        boundary = directory / "boundary-wav"
        _run(
            *_tone_input(duration=60, rate=96_000),
            "-ac",
            "2",
            "-c:a",
            "pcm_s16le",
            "-f",
            "wav",
            "-y",
            str(boundary),
            timeout=60,
        )
        boundary_decoded = await decoder.decode(
            boundary,
            directory / "boundary-pcm",
            declared_mime_type="audio/wav",
            max_seconds=60,
        )
        if not 23_000_000 <= boundary_decoded.pcm_bytes <= MAX_DECODED_BYTES:
            raise AssertionError("Decoded boundary did not exercise the configured output cap")

        too_long = directory / "too-long-wav"
        _run(
            *_tone_input(duration=60.2, rate=8_000),
            "-ac",
            "1",
            "-c:a",
            "pcm_s16le",
            "-f",
            "wav",
            "-y",
            str(too_long),
            timeout=60,
        )
        await _expect_error(
            decoder,
            too_long,
            directory / "too-long-pcm",
            mime_type="audio/wav",
            expected="TOO_LONG",
            max_seconds=60,
        )

    return {
        "status": "passed",
        "accepted": accepted,
        "rejected_cases": [
            "mime_spoof",
            "video_stream",
            "multiple_audio_streams",
            "unsupported_codec",
            "malformed_container",
            "source_size_overflow",
            "duration_overflow",
        ],
        "boundary_pcm_bytes": boundary_decoded.pcm_bytes,
        "device_recordings_tested": False,
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Verify the pinned B-05 decoder with synthetic files."
    )
    parser.parse_args()
    print(json.dumps(asyncio.run(_verify()), sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
